source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'First Banc' do
    pod 'Alamofire', '~> 4.7'
    pod 'ObjectMapper'
    pod 'SkeletonView'
    
  	pod 'Firebase/Core'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Functions'
    pod 'Firebase/Firestore'
  	pod 'lottie-ios'
  	pod 'AlamofireImage'
    pod 'SPLarkController'
    pod 'SwiftyUserDefaults','3.0.1'
end